# Generated by Django 3.2.13 on 2023-07-24 23:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('tin', models.CharField(default='0000000000000', max_length=13, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.IntegerField(null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=40)),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('other_pack', models.CharField(choices=[('BOX', 'BOX'), ('PC', 'PC'), ('CART', 'CART'), ('BOT', 'BOT'), ('SET', 'SET'), ('TRAY', 'TRAY'), ('PACK', 'PACK'), ('CRATE', 'CRATE')], max_length=5, null=True)),
                ('default_pack', models.CharField(choices=[('BOX', 'BOX'), ('PC', 'PC'), ('CART', 'CART'), ('BOT', 'BOT'), ('SET', 'SET'), ('TRAY', 'TRAY'), ('PACK', 'PACK'), ('CRATE', 'CRATE')], max_length=5, null=True)),
                ('max_conv', models.IntegerField(null=True)),
                ('min_conv', models.IntegerField(blank=True, null=True)),
                ('machine', models.BooleanField(default=False)),
                ('parts', models.BooleanField(default=False)),
                ('asset', models.BooleanField(default=False)),
                ('principal', models.CharField(blank=True, choices=[('BD', 'Becton Dickinson'), ('OCD', 'Ortho Clinical Diagnostics'), ('ARK', 'Arkray Co. Ltd')], max_length=4, null=True)),
                ('category', models.CharField(blank=True, choices=[('BDDS', 'BD Diagnostics Systems'), ('BDPAS', 'BD Pre-Analytical Systems'), ('BDB', 'BD Biosciences'), ('MF', 'Vitros Mainframe'), ('IH', 'Vitros Immuno-hematology'), ('IA', 'Vitros Immunoassay')], max_length=7, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.brand')),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor'),
        ),
    ]
