# Generated by Django 3.2.13 on 2023-07-24 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=4, default='0', max_digits=5, null=True)),
                ('delivery_dated', models.DateField(default=django.utils.timezone.now, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_documented', models.DateTimeField(blank=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Documented', 'Documented'), ('Deleted', 'Deleted')], default='Created', max_length=100, null=True)),
                ('sent_to', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_order', to=settings.AUTH_USER_MODEL)),
                ('created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order', to=settings.AUTH_USER_MODEL)),
                ('deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_order', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('convert', models.BooleanField(default=False)),
                ('package', models.CharField(max_length=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('delete_date', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.item')),
                ('request_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.requestorder')),
            ],
        ),
    ]
