# Generated by Django 3.2.13 on 2023-07-25 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_requestitem_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 18, 57, 45, 102541, tzinfo=utc)),
        ),
    ]
