# Generated by Django 3.2.13 on 2023-07-25 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_requestitem_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
