# Generated by Django 3.2.13 on 2023-07-24 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.customuser')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tin', models.CharField(blank=True, max_length=12, null=True)),
                ('sss', models.CharField(blank=True, max_length=10, null=True)),
                ('philhealth', models.CharField(blank=True, max_length=12, null=True)),
                ('pagibig', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
